
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: guodaxia
    url: jdbc:mysql:///blog?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    thymeleaf:
      cache: false
  profiles:
    active: dev




mybatis:
  type-aliases-package: xyz.worldzhi.domain


server:
  servlet:
    context-path: /blog





